baseURL: https://example.com
languageCode: en-us
title: Yourfolio Theme
theme: yourfolio
disableKinds: [RSS, taxonomy, taxonomyTerm]
googleAnalytics: UA-172024038-1

# Menu items
menu:
  main:
  - name: About me
    weight: 2
    url: /about
  - name: Contact
    weight: 3
    url: /contact
  - name: Projects
    weight: 1
    url: /projects

# Custom params
params:
  env: development
  logoImage: img/logo.png
  logoImageAlt: Yourfolio Theme brand logo